/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Bussiness.*;
import static Bussiness.ServiceHocVien.list;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class QLHocVien extends javax.swing.JDialog {
    List<NguoiHoc1>list2=new LinkedList<>();
    DefaultTableModel model,model_nguoihoc;
    DefaultComboBoxModel<String> cbb, cbb_kh;
    Vector<String> list1 = new Vector<>();

    public QLHocVien() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);

        txt_search.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent de) {
search();
                try {
                    nguoihoc();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    Logger.getLogger(QLHocVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
search();
                try {
                    nguoihoc();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    Logger.getLogger(QLHocVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            @Override
            public void changedUpdate(DocumentEvent de) {
search();
                try {
                    nguoihoc();
                } catch (SQLException ex) {
             
                    Logger.getLogger(QLHocVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        cbb = (DefaultComboBoxModel<String>) cbo_khoahoc.getModel();
 model = (DefaultTableModel) tbl_hocvien.getModel();
 model_nguoihoc = (DefaultTableModel) tbl_nguoihoc.getModel();
        loadtoCBBChuyenDe();
        nguoihoc();

    }

    public void loadtoCBBChuyenDe() throws SQLException {
        for (int i = 0; i < ServiceChuyenDe.list.size(); i++) {
            cbo_chuyende.addItem(ServiceChuyenDe.list.get(i).getTencd());
        }
    }

    private void loadTable() {
       
        model.setRowCount(0);
        for (int i = 0; i < ServiceHocVien.list.size(); i++) {
            model.addRow(new Object[]{
                i + 1, ServiceHocVien.list.get(i).getMahv(), ServiceHocVien.list.get(i).getManh(), ServiceHocVien.list.get(i).getHoten(), ServiceHocVien.list.get(i).getDiem()});

        }
    }

    //SELECT *FROM NGUOIHOC WHERE
    //HOTEN LIKE ? AND 
    // MANH NOT IN(SELECT MANH FROM HOCVIEN WHERE MAKH =?)
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbo_chuyende = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        cbo_khoahoc = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_hocvien = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        thongBao = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_nguoihoc = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Chuyên đề");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cbo_chuyende.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_chuyendeItemStateChanged(evt);
            }
        });
        cbo_chuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_chuyendeActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        cbo_khoahoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_khoahocItemStateChanged(evt);
            }
        });
        cbo_khoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_khoahocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbo_khoahoc, 0, 294, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(cbo_khoahoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbo_chuyende, 0, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(cbo_chuyende, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Khóa học");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(246, 246, 246)
                        .addComponent(jLabel2))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        tbl_hocvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TT", "Mã hv", "Mã NH", "Họ tên", "Điểm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_hocvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_hocvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_hocvien);
        if (tbl_hocvien.getColumnModel().getColumnCount() > 0) {
            tbl_hocvien.getColumnModel().getColumn(0).setResizable(false);
            tbl_hocvien.getColumnModel().getColumn(1).setResizable(false);
            tbl_hocvien.getColumnModel().getColumn(2).setResizable(false);
            tbl_hocvien.getColumnModel().getColumn(3).setResizable(false);
            tbl_hocvien.getColumnModel().getColumn(4).setResizable(false);
        }

        jButton2.setText("Xóa khỏi khóa học");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("cập nhật điểm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(69, 69, 69))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)))
        );

        jTabbedPane1.addTab("Học viên", jPanel4);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("Tìm kiếm");

        txt_search.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txt_searchCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txt_searchInputMethodTextChanged(evt);
            }
        });
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 581, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(txt_search)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        tbl_nguoihoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NH", "Họ Tên", "Giới tính", "Ngày sinh", "Điện thoại", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_nguoihoc);
        if (tbl_nguoihoc.getColumnModel().getColumnCount() > 0) {
            tbl_nguoihoc.getColumnModel().getColumn(0).setResizable(false);
            tbl_nguoihoc.getColumnModel().getColumn(2).setResizable(false);
            tbl_nguoihoc.getColumnModel().getColumn(3).setResizable(false);
            tbl_nguoihoc.getColumnModel().getColumn(4).setResizable(false);
        }

        jButton1.setText("Thêm vào học viên");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout thongBaoLayout = new javax.swing.GroupLayout(thongBao);
        thongBao.setLayout(thongBaoLayout);
        thongBaoLayout.setHorizontalGroup(
            thongBaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thongBaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        thongBaoLayout.setVerticalGroup(
            thongBaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thongBaoLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );

        jTabbedPane1.addTab("Người học", thongBao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void loadCBBKhoahoc() throws SQLException {
        String query = "	select chuyende.macd,ngaykg from chuyende join KHOAHOC\n"
                + "			      on CHUYENDE.MACD=KHOAHOC.MACD\n"
                + "               \n"
                + "               where TENCD = ?";
        PreparedStatement pre = ConnectSQLServer.Connect.con.prepareStatement(query);
        pre.setString(1, String.valueOf(cbo_chuyende.getSelectedItem()));
        ResultSet rs = pre.executeQuery();
        while (rs.next()) {
            cbb.addElement(rs.getString(1) + "(" + rs.getString(2) + ")");
            list1.add(rs.getString(1));
        }

    }
    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed
void updateDiem(){
    int index=tbl_hocvien.getSelectedRow();
    String diem=JOptionPane.showInputDialog("Mời bạn nhập điểm", tbl_hocvien.getValueAt(index, 4));
    try {
        if(diem.equals("")){
            JOptionPane.showMessageDialog(this,"Điểm không được bỏ trống");
            return;
        }
        if(diem.matches("[-+]?[0-9]*\\.?[0-9]+$")==false){
            JOptionPane.showMessageDialog(this,"Điểm phải là số");
            return;
        }
        if(Double.valueOf(diem)>10||Double.valueOf(diem)<0){
            JOptionPane.showMessageDialog(this,"Điểm nhập vào không hợp lệ");
            return;
        }
        if(CRUD.CRUD_HocVien.update(Double.valueOf(diem), (int) tbl_hocvien.getValueAt(index, 1))>0){
             addtoTable();
            JOptionPane.showMessageDialog(this, "Sửa điểm thành công");
           
       
        }
        
    } catch (Exception e) {
        e.printStackTrace();
    }
}
void search(){
    for (int i = 0; i <list2.size(); i++) {
        if(list2.get(i).getHoten().contains(txt_search.getText())){
            model_nguoihoc.setRowCount(0);
            model_nguoihoc.addRow(new Object[]{
              list2.get(i).getManh(),list2.get(i).getHoten(),list2.get(i).getGt(),list2.get(i).getNgaysinh(),
                list2.get(i).getDt(),list2.get(i).getEmail()
            });
        }
        
    }
}
String Getgt(int gt){
    if(gt==1)return "nam";
    return "nữ";
}
void nguoihoc() throws SQLException{
    String query="select manh,HOTEN,GIOITINH,ngaysinh,DIENTHOAI,EMAIL from nguoihoc where\n" +
"manh not in(select nguoihoc.manh from hocvien join KHOAHOC on HOCVIEN.MAKH=KHOAHOC.MAKH\n" +
"join CHUYENDE on CHUYENDE.MACD=KHOAHOC.MACD join NGUOIHOC on NGUOIHOC.MANH=HOCVIEN.MANH)";
    PreparedStatement pre=ConnectSQLServer.Connect.con.prepareStatement(query);
    ResultSet rs=pre.executeQuery();
    while (rs.next()) {    
       list2.add(new NguoiHoc1( rs.getString(1),rs.getString(2),Getgt(rs.getInt(3)),rs.getString(4),rs.getString(5),rs.getString(6)));
        model_nguoihoc.addRow(new Object[]{
        rs.getString(1),rs.getString(2),Getgt(rs.getInt(3)),rs.getString(4),rs.getString(5),rs.getString(6)});
    }
}
void addtoTable() throws SQLException{
    model.setRowCount(0);
    String query="select HOCVIEN.MAHV,HOCVIEN.MAKH,NGUOIHOC.hoten,HOCVIEN.DIEM from hocvien join KHOAHOC on HOCVIEN.MAKH=KHOAHOC.MAKH\n" +
"join CHUYENDE on CHUYENDE.MACD=KHOAHOC.MACD join NGUOIHOC on NGUOIHOC.MANH=HOCVIEN.MANH\n" +
"where TENCD=? and chuyende.MACD=?";
     String a = String.valueOf(cbb.getSelectedItem());
          String  b = a.substring(0, a.lastIndexOf("("));
    PreparedStatement pre=ConnectSQLServer.Connect.con.prepareStatement(query);
    pre.setString(1, String.valueOf(cbo_chuyende.getSelectedItem()));
    pre.setString(2, b);
    ResultSet rs=pre.executeQuery();
    while (rs.next()) {        
        int i=1;
        model.addRow(new Object[]{i,rs.getInt(1),rs.getString(2),rs.getString(3),rs.getDouble(4)});
        i++;
    }
}
    private void cbo_chuyendeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_chuyendeItemStateChanged
        try {
            model = (DefaultTableModel) tbl_hocvien.getModel();
            model.setRowCount(0);
            cbb.removeAllElements();

            loadCBBKhoahoc();

        } catch (SQLException ex) {
            ex.printStackTrace();
            Logger.getLogger(QLHocVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbo_chuyendeItemStateChanged

    private void txt_searchInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt_searchInputMethodTextChanged

    }//GEN-LAST:event_txt_searchInputMethodTextChanged

    private void txt_searchCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt_searchCaretPositionChanged

    }//GEN-LAST:event_txt_searchCaretPositionChanged

    private void cbo_chuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_chuyendeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_chuyendeActionPerformed
    void loadcbbToTable() {
        String b;
        if (cbb.getSize() == 0) {
            b = "";
        } else {
            String a = String.valueOf(cbb.getSelectedItem());
            b = a.substring(0, a.lastIndexOf("("));
        }

        try {
            String query = "select mahv,nguoihoc.manh,hoten,diem from NGUOIHOC join HOCVIEN\n"
                    + "on NGUOIHOC.MANH=HOCVIEN.MANH join KHOAHOC on HOCVIEN.MAKH=KHOAHOC.MAKH\n"
                    + "where macd=?";
            PreparedStatement pre = ConnectSQLServer.Connect.con.prepareStatement(query);
            pre.setString(1, b);
            ResultSet rs = pre.executeQuery();
            while (rs.next()) {
                list.add(new HocVien(rs.getInt(1), rs.getString(2), rs.getString(3), rs.getDouble(4)));
            }

            loadTable();
        } catch (SQLException ex) {
            Logger.getLogger(QLHocVien.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void cbo_khoahocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_khoahocItemStateChanged

        model = (DefaultTableModel) tbl_hocvien.getModel();
        model.setRowCount(0);
        loadcbbToTable();
    }//GEN-LAST:event_cbo_khoahocItemStateChanged

    private void cbo_khoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_khoahocActionPerformed


    }//GEN-LAST:event_cbo_khoahocActionPerformed

    private void tbl_hocvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_hocvienMouseClicked

    }//GEN-LAST:event_tbl_hocvienMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      updateDiem();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   int chon=JOptionPane.showConfirmDialog(this,"bạn muốn xóa không","Hỏi",JOptionPane.YES_NO_OPTION);
     if(chon==0){
            String sql="delete from hocvien where mahv=?";
    int index=tbl_hocvien.getSelectedRow();
    PreparedStatement pre;
        try {
            pre = ConnectSQLServer.Connect.con.prepareStatement(sql);
              pre.setInt(1,Integer.parseInt(tbl_hocvien.getValueAt(index,1).toString()));
              if(pre.executeUpdate()>0){
                  JOptionPane.showMessageDialog(this,"Xóa thành công");
                  addtoTable();
                  nguoihoc();
              }
        } catch (SQLException ex) {
            Logger.getLogger(QLHocVien.class.getName()).log(Level.SEVERE, null, ex);
        }
  
     }
    }//GEN-LAST:event_jButton2ActionPerformed
int getMKH(String macd) throws SQLException{
    String sql="Select makh from khoahoc where macd=?";
      
    PreparedStatement pre=ConnectSQLServer.Connect.con.prepareStatement(sql);
    pre.setString(1, macd);
    ResultSet rs=pre.executeQuery();
    while (rs.next()) {        
        return rs.getInt(1);
    }
    return -1;
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String sql="insert into hocvien values(?,?,?)";
    PreparedStatement pre;
  String a=String.valueOf(cbb.getSelectedItem());
    String b=a.substring(0,a.lastIndexOf("("));
    int index=tbl_nguoihoc.getSelectedRow();
    
        try {
            pre = ConnectSQLServer.Connect.con.prepareStatement(sql);
             pre.setInt(1,getMKH(b));
             pre.setString(2, String.valueOf(tbl_nguoihoc.getValueAt(index, 0)));
             pre.setDouble(3, 0);
             if(pre.executeUpdate()>0){
                 JOptionPane.showMessageDialog(this, "thêm thành công");
                 addtoTable();
                 model_nguoihoc.setRowCount(0);
                 nguoihoc();
             }
        } catch (SQLException ex) {
            Logger.getLogger(QLHocVien.class.getName()).log(Level.SEVERE, null, ex);
        }
   
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLHocVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLHocVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLHocVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLHocVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new QLHocVien().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(QLHocVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbo_chuyende;
    private javax.swing.JComboBox<String> cbo_khoahoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbl_hocvien;
    private javax.swing.JTable tbl_nguoihoc;
    private javax.swing.JPanel thongBao;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
class NguoiHoc1{
    private String manh;
    private String hoten;
    private String gt;
    private String ngaysinh;
    private String dt;
    private String email;

    public NguoiHoc1() {
    }

    public NguoiHoc1(String manh, String hoten, String gt, String ngaysinh, String dt, String email) {
        this.manh = manh;
        this.hoten = hoten;
        this.gt = gt;
        this.ngaysinh = ngaysinh;
        this.dt = dt;
        this.email = email;
    }

    public String getManh() {
        return manh;
    }

    public void setManh(String manh) {
        this.manh = manh;
    }

    public String getHoten() {
        return hoten;
    }

    public void setHoten(String hoten) {
        this.hoten = hoten;
    }

    public String getGt() {
        return gt;
    }

    public void setGt(String gt) {
        this.gt = gt;
    }

    public String getNgaysinh() {
        return ngaysinh;
    }

    public void setNgaysinh(String ngaysinh) {
        this.ngaysinh = ngaysinh;
    }

    public String getDt() {
        return dt;
    }

    public void setDt(String dt) {
        this.dt = dt;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    
}